### PR TITLE
Unblock Windows && Linux

### LINKED ISSUE #194: "cmd" alternative for Windows
Some of the UI tooltips mention a "cmd" key, which doesn't exist in Windows. Commands which use the "cmd" key don't seem to work when using any of the common Windows modifier keys. I tried ctrl, alt, fn, and the Windows key. Ctrl is usually the one.

If VisBug does have alternative Windows bindings, the UI tooltips should display them for Windows users. If the alternatives don't exist, then VisBug is partially broken on Windows!

Apologies if I've missed something here.

### PR DESCRIPTION
**Pull request by argyleink**
fixes #194 

please try this out folks! it's functionally complete, but i need to update some other assets, like the demo page and wiki and stuff.. help me find what's missing!?

Windows or Linux users who want to test!
- clone this fork/branch
- npm i
- npm start
- visit localhost:3000 and give it a test!

### CODE REVIEW

**Comment by argyleink** [comment]
screenshot from 2018-12-05 16-31-18

**Comment by dgeare** [comment]
Can confirm, works on windows. Only had 15 minutes to test it this morning, but I was able to verify each tool functioned. Thanks @argyleink!

**Comment by argyleink** [comment]
screenshot from 2018-12-06 09-48-20

alt and ctrl shown

**Comment by argyleink** [comment]
1 or 2 bug fixes in the keyboard trainers, but other than that i think this is good to go. anyone else want to give it a go before i merge? also, if you give this PR a try, go ahead and put your stamp of approval on here! thanks!

**Comment by dgeare** [comment]
🎉🎉🎉

**Pull request merged**
