### PR TITLE
Changing README.md to uppercase

### PR DESCRIPTION
**Pull request by Rafi993**
I just changed **README.md** to uppercase when I saw this source I could not ignore it.

### CODE REVIEW

**Comment by Rafi993** [comment]
I signed it!

**Comment by Rafi993** [comment]
None. It is just default thing that people and websites like Github do by default. Just to consistent with other repos.

**Comment by Rafi993** [comment]
https://softwareengineering.stackexchange.com/a/301708

**Comment by argyleink** [comment]
i see where you were going with this, but i dont think it's needed. thanks for contributing, but this one i'm going to reject, sorry!

**Pull request closed without merging**
